FROM node:20-bookworm-slim AS base

ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runner
WORKDIR /app

ARG PORT=3000
ARG HOSTNAME=0.0.0.0
ARG SQLITE_DATA_DIR=/app/data
ARG WEBAUTHN_RP_ID=localhost
ARG WEBAUTHN_ORIGIN=http://localhost:3000
ARG WEBAUTHN_REQUIRE_USER_VERIFICATION=false
ARG SESSION_COOKIE_NAME=newsclaw_session
ARG NEWSCLAW_KEY_ENCRYPTION_SECRET=
ARG OPENAI_API_KEY=
ARG OPENAI_SKILL_MODEL=gpt-4.1-mini
ARG NEWSCLAW_SKILL_DIR=./newsclaw-skills
ARG CLAWMACDO_SNAPSHOT_NAME=
ARG CLAWMACDO_INSTANCE_SIZE=s-2vcpu-4gb
ARG AWS_ACCESS_KEY_ID=
ARG AWS_SECRET_ACCESS_KEY=
ARG AWS_REGION=ap-southeast-1
ARG AWS_CONFIG_FILE=
ARG AWS_CLI_BIN=aws
ARG CLAWMACDO_BIN=

ENV NODE_ENV=production \
	PORT=${PORT} \
	HOSTNAME=${HOSTNAME} \
	SQLITE_DATA_DIR=${SQLITE_DATA_DIR} \
	WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID} \
	WEBAUTHN_ORIGIN=${WEBAUTHN_ORIGIN} \
	WEBAUTHN_REQUIRE_USER_VERIFICATION=${WEBAUTHN_REQUIRE_USER_VERIFICATION} \
	SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME} \
	NEWSCLAW_KEY_ENCRYPTION_SECRET=${NEWSCLAW_KEY_ENCRYPTION_SECRET} \
	OPENAI_API_KEY=${OPENAI_API_KEY} \
	OPENAI_SKILL_MODEL=${OPENAI_SKILL_MODEL} \
	NEWSCLAW_SKILL_DIR=${NEWSCLAW_SKILL_DIR} \
	CLAWMACDO_SNAPSHOT_NAME=${CLAWMACDO_SNAPSHOT_NAME} \
	CLAWMACDO_INSTANCE_SIZE=${CLAWMACDO_INSTANCE_SIZE} \
	AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
	AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
	AWS_REGION=${AWS_REGION} \
	AWS_CONFIG_FILE=${AWS_CONFIG_FILE} \
	AWS_CLI_BIN=${AWS_CLI_BIN} \
	CLAWMACDO_BIN=${CLAWMACDO_BIN}

COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/next.config.ts ./next.config.ts

RUN chmod +x /app/scripts/start-container.sh && mkdir -p /app/data

EXPOSE 3000

CMD ["/app/scripts/start-container.sh"]